/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as veBudsSol from "./VeBuds.sol";
export { BakelandDAO__factory } from "./BakelandDAO__factory";
export { Timelock__factory } from "./Timelock__factory";
