/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iWormholeRelayerSol from "./IWormholeRelayer.sol";
export type { iWormholeRelayerSol };
export type { IWormhole } from "./IWormhole";
export type { IWormholeReceiver } from "./IWormholeReceiver";
