/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as veBudsSol from "./VeBuds.sol";
export type { veBudsSol };
export type { BakelandDAO } from "./BakelandDAO";
export type { Timelock } from "./Timelock";
